# Generated by Django 5.2 on 2025-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('sms', 'SMS')], default='web', max_length=10),
        ),
    ]
