# Generated by Django 5.2 on 2025-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEB', 'Web')], max_length=10),
        ),
    ]
