# Generated by Django 5.2 on 2025-05-12 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rapport_date_debut_alter_rapport_date_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('YARA', 'Analyse YARA'), ('SIGMA', 'Règle SIGMA'), ('CORRELATION', 'Corrélation')], max_length=20)),
                ('fichier_analyse', models.CharField(blank=True, max_length=255, null=True)),
                ('resultat', models.JSONField()),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('severite', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10)),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rapport')),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.regle')),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('score_confiance', models.FloatField(default=0.0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('menace', models.CharField(blank=True, max_length=255, null=True)),
                ('resultats', models.ManyToManyField(related_name='correlations', to='users.resultatanalyse')),
            ],
            options={
                'ordering': ['-score_confiance', '-date_creation'],
            },
        ),
    ]
